apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
    env: prod
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: api
          image: 443370706049.dkr.ecr.us-east-1.amazonaws.com/backend:5
          imagePullPolicy: Always
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
            - name: MONGO_HOST
              value: "mongodb-svc"
            - name: MONGO_DB
              value: "projet_memoire"
            - name: USE_DB_AUTH
              value: "true"
          ports:
            - containerPort: 5000
